"""Init

Revision ID: 189b4a846c9d
Revises: 
Create Date: 2019-02-05 19:23:54.211697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189b4a846c9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Candidates',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.UniqueConstraint('id')
    )
    op.create_table('Inerviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('candidate', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate'], ['Candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Inerviews')
    op.drop_table('Candidates')
    # ### end Alembic commands ###
