"""add-pk

Revision ID: 38bdbf24dd4a
Revises: d247828b493c
Create Date: 2019-04-22 11:07:54.213844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38bdbf24dd4a'
down_revision = 'd247828b493c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'interviews', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='unique')
    # ### end Alembic commands ###
