"""add-jobs

Revision ID: d247828b493c
Revises: 189b4a846c9d
Create Date: 2019-04-17 15:59:08.643554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd247828b493c'
down_revision = '189b4a846c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('jobs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'jobs')
    # ### end Alembic commands ###
